import { AppDataSource } from '../datasource';
import { Siswa } from '../entities/entities/Siswa';

export async function siswaSeeder() {
  const siswaRepository = AppDataSource.getRepository(Siswa);

  const dataSiswa = [
    {
      nisn: '0135344834',
      nis: '13681',
      namaLengkap: 'Adji Shobri Wa Shola',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2013-04-02',
      alamat: 'Lingk. Sale RT 33 RW 6, Kel Plaosan, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3121808342',
      nis: '13682',
      namaLengkap: 'Afang Fertindo Junianta',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-06-21',
      alamat: 'Bogosari RT 3 Rw 1 Ds Bogoarum, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3128594676',
      nis: '13683',
      namaLengkap: 'Afifa Pradila Maharani',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-10-19',
      alamat: 'Gupakan RT 15 RW 8 Ds. Dadi - Kec. Plaosan - Kab. Magetan',
      statusAktif: true,
    },
    {
      nisn: '3128661873',
      nis: '13684',
      namaLengkap: 'Alif Riansi Saputra',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-12-30',
      alamat: 'RT 003 RW 001, Sarangan, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '0129477955',
      nis: '13685',
      namaLengkap: 'Aprilya Maharani',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-04-12',
      alamat: 'Dele RT 3 RW 1 Ds. Buluharjo - Kec. Plaosan - Kab. Magetan',
      statusAktif: true,
    },
    {
      nisn: '3147461482',
      nis: '13686',
      namaLengkap: 'Aqilah Salsabila',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Semarang',
      tanggalLahir: '2014-01-06',
      alamat: 'Gupakan RT 019 RW 010, Ds. Dadi, - Kec. Plaosan - Kab. Magetan',
      statusAktif: true,
    },
    {
      nisn: '3129334094',
      nis: '13687',
      namaLengkap: 'Arya Shuta Kalindra',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-09-10',
      alamat: 'RT.022 RW.003 Ds. Pacalan - Kec. Plaosan - Kab. Magetan',
      statusAktif: true,
    },
    {
      nisn: '0126348852',
      nis: '13688',
      namaLengkap: 'Asifa Yessa Bella',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-11-01',
      alamat: 'RT 17 RW 4 Ds. Puntukdoro - Kec. Plaosan - Kab. Magetan',
      statusAktif: true,
    },
    {
      nisn: '0126576251',
      nis: '13689',
      namaLengkap: 'Brian Prabaswara Budianto',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Purworejo',
      tanggalLahir: '2012-09-19',
      alamat: 'JLN KALIURANG, CONDONGCATUR-DEPOK',
      statusAktif: true,
    },
    {
      nisn: '0136715473',
      nis: '13690',
      namaLengkap: 'Caroline Syabila Alvaro Janitra',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2013-01-24',
      alamat: 'Klaten RT 22 RW 5 Ds. Puntukdoro - Kec. Plaosan - Kab. Magetan',
      statusAktif: true,
    },
    {
      nisn: '3124563994',
      nis: '13713',
      namaLengkap: 'Afika Ardina Maharani',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-08-05',
      alamat: 'Gulun, RT 003 RW 004, Kel Plaosan - Kec. Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '0122169515',
      nis: '13714',
      namaLengkap: 'Afnan Junio Alfiansah',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-06-18',
      alamat: 'Compok RT 2 RW 1, Dadi - Kec. Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '0128693037',
      nis: '13715',
      namaLengkap: 'Afriska Mega Tania',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-08-08',
      alamat: 'Gulun, RT 29 RW 5, Kel Plaosan - Kec. Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3121181459',
      nis: '13716',
      namaLengkap: 'Alim Fahrudin Naafi\'i',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-06-20',
      alamat: 'RT 28 RW 14 Ds Dadi, - Kec. Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3123768290',
      nis: '13717',
      namaLengkap: 'Ardita Putri Natasyila',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-05-14',
      alamat: 'Rt 13 Rw 07 Dsn Ngerong, Dadi - Kec. Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '0135206837',
      nis: '13718',
      namaLengkap: 'Arga Setyo Pambudi',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2013-05-19',
      alamat: 'Kauman RT 29 RW 5, Plaosan - Kec. Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3136408972',
      nis: '13719',
      namaLengkap: 'Arsyafin Nuril Wafi Razaki',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2013-01-06',
      alamat: 'Karanglo RT 6 RW 2, Bogoarum - Kec. Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3129013066',
      nis: '13720',
      namaLengkap: 'Azwar Maulana',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-12-20',
      alamat: 'Sarangan RT 2 RW 1, Sarangan - Kec. Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3120995590',
      nis: '13721',
      namaLengkap: 'Cherizca Karunia Ragil Widhuri',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-02-01',
      alamat: 'Dsn Tawang RT 006 RW 001, Bulugunung - Kec. Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3128308461',
      nis: '13722',
      namaLengkap: 'Damar Pambudi',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-10-23',
      alamat: 'RT 23 RW 12 Ds Dadi - Kec. Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '0115237829',
      nis: '13402',
      namaLengkap: 'Adelia Qhalitza Ramadhani',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2011-08-28',
      alamat: 'Compok RT 2 RW 1 Ds Dadi - Kec. Plaosan - Kab. Magetan',
      statusAktif: true,
    },
    {
      nisn: '0116134287',
      nis: '13403',
      namaLengkap: 'Aditya Rifki Fauzi',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Kota Bekasi',
      tanggalLahir: '2011-03-21',
      alamat: 'Dele RT 2 RW 1 Ds Buluharjo - Kec. Plaosan - Kab. Magetan',
      statusAktif: true,
    },
    {
      nisn: '0111700226',
      nis: '13404',
      namaLengkap: 'Aisyah Siti Nuraini',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2011-07-26',
      alamat: 'Klaten RT 25 RW 5 Ds Puntukdoro - Kec. Plaosan - Kab. Magetan',
      statusAktif: true,
    },
    {
      nisn: '0116053970',
      nis: '13405',
      namaLengkap: 'Aldina Yasmin Naya Azzahra',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2011-09-24',
      alamat: 'Singolangu RT 14 RW 3 Kel. Sarangan - Kec. Plaosan - Kab. Magetan',
      statusAktif: true,
    },
    {
      nisn: '0112552708',
      nis: '13406',
      namaLengkap: 'Aleesya Zahraa Anggraeni',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2011-10-25',
      alamat: 'RT 17 RW 3 Ds. Plumpung - Kec. Plaosan - Kab. Magetan',
      statusAktif: true,
    },
    {
      nisn: '0122197554',
      nis: '13407',
      namaLengkap: 'Alvian Khafkha Pratama',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-03-14',
      alamat: 'Ds. Plaosan, RT. 16/ 02, Kec. Plaosan, Kab. Magetan',
      statusAktif: true,
    },
    {
      nisn: '0113751614',
      nis: '13408',
      namaLengkap: 'Anis Nova Ariyanti',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2011-11-13',
      alamat: 'Link Plaosan RT 4 RW 2 Kel Plaosan - Kec. Plaosan - Kab. Magetan',
      statusAktif: true,
    },
    {
      nisn: '0121222473',
      nis: '13409',
      namaLengkap: 'Avika Azalia Surya Putri',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-05-06',
      alamat: 'Buket RT 1 RW 1 Ds Bulugunung - Kec. Plaosan - Kab. Magetan',
      statusAktif: true,
    },
    {
      nisn: '0117423123',
      nis: '13410',
      namaLengkap: 'Azzahra Roudhotul Jannah',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2011-09-06',
      alamat: 'Klaten RT 25 RW 5 Ds. Puntukdoro - Kec. Plaosan - Kab. Magetan',
      statusAktif: true,
    },
    {
      nisn: '0118749633',
      nis: '13411',
      namaLengkap: 'Bilqis Pury Santika',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2011-09-18',
      alamat: 'Geneng RT 36 RW 3 Ds. Pacalan - Kec. Plaosan - Kab. Magetan',
      statusAktif: true,
    },
    {
      nisn: '0118070978',
      nis: '13146',
      namaLengkap: 'Aditya Nur Safari Pradipta',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2011-01-09',
      alamat: 'RT 02 RW 01 Ngancar, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '0104264876',
      nis: '13147',
      namaLengkap: 'Airin Novita Sari',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2010-11-01',
      alamat: 'Compok RT 01 RW 01, Dadi, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '0117732619',
      nis: '13148',
      namaLengkap: 'Alfian Alam Khanza Syafa\'',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2011-10-18',
      alamat: 'RT 02 RW 01, Ngancar, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '0101935729',
      nis: '13149',
      namaLengkap: 'Alisya Mega Putri',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2010-12-02',
      alamat: 'Buket RT 09 RW 01, Bulugunung, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '0103507064',
      nis: '13150',
      namaLengkap: 'Anaya Anandari',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2010-08-04',
      alamat: 'Kandenan RT 39 RW 7 Plaosan, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '0115894273',
      nis: '13151',
      namaLengkap: 'Bima Abdillah Alkais',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2011-05-19',
      alamat: 'RT 18 RW 4 Puntukdoro, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '0118369152',
      nis: '13152',
      namaLengkap: 'Chelsea Terra Himara',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2011-03-27',
      alamat: 'Singolangu RT 13 RW 3, Sarangan, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '0106563335',
      nis: '13153',
      namaLengkap: 'Damar Putra Mahameru',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Kupang',
      tanggalLahir: '2010-03-20',
      alamat: 'Pakel RT 7 RT 3, Dadi, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '0113969364',
      nis: '13154',
      namaLengkap: 'Dony Irawan',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2011-02-09',
      alamat: 'Gulun RT 22 RW 03 Kel Plaosan, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '0117913569',
      nis: '13155',
      namaLengkap: 'Ervina Putri Magdalena',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2011-02-26',
      alamat: 'RT 27 RW 14 Dadi, Plaosan, Magetan',
      statusAktif: true,
    },
  ];

  let insertedCount = 0;

  for (const item of dataSiswa) {
    const existing = await siswaRepository.findOne({
      where: {
        nisn: item.nisn,
      },
    });

    if (!existing) {
      const siswa = siswaRepository.create(item);
      await siswaRepository.save(siswa);
      insertedCount++;
    }
  }

  console.log('======================================');
  console.log(`\u2714 Seeder Siswa selesai dijalankan.`);
  console.log(`Total data baru ditambahkan : ${insertedCount}`);
  console.log('======================================');
}