import { AppDataSource } from '../datasource';
import { Siswa } from '../entities/entities/Siswa';

export async function siswaSeeder() {
  const siswaRepository = AppDataSource.getRepository(Siswa);

  const dataSiswa = [
    {
      nisn: '135344834',
      nis: '13681',
      namaLengkap: 'Adji Shobri Wa Shola',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2013-04-02',
      alamat: 'Lingk. Sale RT 33 RW 6, Kel Plaosan, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3121808342',
      nis: '13682',
      namaLengkap: 'Afang Fertindo Junianta',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-06-21',
      alamat: 'Bogosari RT 3 Rw 1 Ds Bogoarum, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3128595304',
      nis: '13683',
      namaLengkap: 'Afifa Pradila Maharani',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-10-19',
      alamat: 'Gupakan RT 15 RW 8 Ds. Dadi - Kec. Plaosan - Kab. Magetan',
      statusAktif: true,
    },
    {
      nisn: '3128662057',
      nis: '13684',
      namaLengkap: 'Alif Riansi Saputra',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-12-30',
      alamat: 'RT 003 RW 001, Sarangan, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3122176311',
      nis: '13685',
      namaLengkap: 'Ananda Cahya Pitaloka',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-08-01',
      alamat: 'Mandangu RT 11 RW 2, Sumberagung, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3123842186',
      nis: '13686',
      namaLengkap: 'Andien Sifa Audia Prameswari',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-06-18',
      alamat: 'RT 13 RW 03, Sumberagung, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3120689972',
      nis: '13687',
      namaLengkap: 'Aquila Kirana Bening Sakti',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Surakarta',
      tanggalLahir: '2012-09-08',
      alamat: 'RT 23 RW 03 Dsn. Pandean Ds. Bulugunung',
      statusAktif: true,
    },
    {
      nisn: '3126487143',
      nis: '13688',
      namaLengkap: 'Aresa Danendra Zaki Alfatih',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-06-12',
      alamat: 'Kec. Plaosan - Kab. Magetan',
      statusAktif: true,
    },
    {
      nisn: '3122709210',
      nis: '13689',
      namaLengkap: 'Arin Safira',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-04-18',
      alamat: 'Plumpung RT 25 RW 4, Simbatan, Sarangan, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3135832724',
      nis: '13690',
      namaLengkap: 'Azkia Nida Kamila',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2013-05-18',
      alamat: 'Lingk. Pacalan RT 05 RW 01, Kel. Pacalan, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3138805213',
      nis: '13691',
      namaLengkap: 'Chesy Zora Anindita',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2013-04-09',
      alamat: 'RT 009 RW 002, Nitikan, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3124584224',
      nis: '13692',
      namaLengkap: 'Dafiyan Restu Firmansyah',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-09-06',
      alamat: 'Kec. Plaosan - Kab. Magetan',
      statusAktif: true,
    },
    {
      nisn: '3121175654',
      nis: '13693',
      namaLengkap: 'Earlyta Arsyfa Salsabila',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-10-18',
      alamat: 'Lingk. Sale RT 31 RW 06, Plaosan, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3125217430',
      nis: '13694',
      namaLengkap: 'Fardhan Aji Pangestu',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-10-09',
      alamat: 'Singolangu RT 15 RW 3, Sarangan, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3136528876',
      nis: '13695',
      namaLengkap: 'Fradea Aliefa Setyo Anggoro',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2013-03-08',
      alamat: 'Lingk. Pacalan RT 05 RW 01, Kel. Pacalan, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3130453303',
      nis: '13696',
      namaLengkap: 'Habiburrohman Ramadhan A.',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Sidoarjo',
      tanggalLahir: '2013-07-16',
      alamat: 'Gandon, RT 003 RW 001, Ds. Sukowidi',
      statusAktif: true,
    },
    {
      nisn: '3129845339',
      nis: '13697',
      namaLengkap: 'Hanan Mufia Pradita',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-09-27',
      alamat: 'RT 003 RW 001, Nitikan, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3133379563',
      nis: '13698',
      namaLengkap: 'Hilal Rasyid Nurrohman',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2013-01-20',
      alamat: 'Dsn Bulusari RT 16 RW 03, Bulugunung, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3128911571',
      nis: '13699',
      namaLengkap: 'Javas Farrel Aji Pamungkas',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-08-04',
      alamat: 'Ngluweng RT 19 RW 3, Ngancar, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3127814298',
      nis: '13700',
      namaLengkap: 'Kaila Bunga Auliya',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-10-18',
      alamat: 'RT 012 RW 002, Nitikan, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3129486241',
      nis: '13701',
      namaLengkap: 'Khenzo Arya Bima Pratama',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-11-20',
      alamat: 'Ngluweng RT 17 RW 3, Ngancar, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3129337095',
      nis: '13702',
      namaLengkap: 'Kurnia Dewi Novitasari',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-11-25',
      alamat: 'Kec. Plaosan - Kab. Magetan',
      statusAktif: true,
    },
    {
      nisn: '3128366911',
      nis: '13703',
      namaLengkap: 'Muhammad Alfaro Putra R.',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-10-23',
      alamat: 'Mogag RT 18 RW 03, Pocol, Samirejo, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3120612265',
      nis: '13704',
      namaLengkap: 'M. Azril Tri Ramadhani',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-08-04',
      alamat: 'Namporejo RT 01 RW 01, Sumberagung, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3138806297',
      nis: '13705',
      namaLengkap: 'Muhammad Bintang Ramadhan',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2013-07-21',
      alamat: 'RT 003 RW 001, Nitikan, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3120692737',
      nis: '13706',
      namaLengkap: 'Mohammad Farrel Dwi Febrian',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-02-14',
      alamat: 'RT 11 RW 02, Bulugunung, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3126868661',
      nis: '13707',
      namaLengkap: 'Mohammad Rafli Bima Pangestu',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-11-04',
      alamat: 'Kec. Plaosan - Kab. Magetan',
      statusAktif: true,
    },
    {
      nisn: '3124803978',
      nis: '13708',
      namaLengkap: 'M. Wildan Al Firdaus',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-08-25',
      alamat: 'RT 18 RW 03, Buluhardjo, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3136224169',
      nis: '13709',
      namaLengkap: 'Mukhammad Iqbal Maulana',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Surabaya',
      tanggalLahir: '2013-02-14',
      alamat: 'Bogoarum RT 02 RW 01, Bogoarum, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3124784917',
      nis: '13710',
      namaLengkap: 'Priska Wulan Fitriana',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-08-29',
      alamat: 'Bondjen RT 04 RW 01, Bulugunung, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3125219430',
      nis: '13711',
      namaLengkap: 'Raya Adya Faza Farzanah',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-10-18',
      alamat: 'RT 004 RW 001, Nitikan, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3126620573',
      nis: '13712',
      namaLengkap: 'Relies Bagus Saputra',
      jenisKelamin: 'L' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-09-08',
      alamat: 'RT 003 RW 001, Sarangan, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3123899201',
      nis: '13713',
      namaLengkap: 'Reva Dwi Anjani',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-10-23',
      alamat: 'RT 007 RW 002, Nitikan, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3124239857',
      nis: '13714',
      namaLengkap: 'Silvi Novia Safitri',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-11-03',
      alamat: 'Bogonjan RT 04 RW 01, Bulugunung, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3138356972',
      nis: '13715',
      namaLengkap: 'Stania Aulia Putri',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2013-01-09',
      alamat: 'Lingk. Sidorejo RT 20 RW 4, Plaosan, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3126868846',
      nis: '13716',
      namaLengkap: 'Syaifa Maulida Ardhani',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-10-21',
      alamat: 'Mandangu RT 11 RW 2, Sumberagung, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3133379201',
      nis: '13717',
      namaLengkap: 'Syakira Ainun Mahya',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2013-03-01',
      alamat: 'Dadi RT 02 RW 01, Dadi, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3134237190',
      nis: '13718',
      namaLengkap: 'Wening Galih Pangastuti',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2013-02-12',
      alamat: 'Lingk. Plaosan RT 11 RW 2, Plaosan, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3126071982',
      nis: '13719',
      namaLengkap: 'Yielda Aulia Az Zahra',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-12-10',
      alamat: 'Lingk. Plaosan RT 12 RW 2, Plaosan, Plaosan, Magetan',
      statusAktif: true,
    },
    {
      nisn: '3128821960',
      nis: '13720',
      namaLengkap: 'Zaskia Bunga Pertiwi',
      jenisKelamin: 'P' as const,
      tempatLahir: 'Magetan',
      tanggalLahir: '2012-09-08',
      alamat: 'RT 005 RW 001, Sarangan, Plaosan, Magetan',
      statusAktif: true,
    },
  ];

  let insertedCount = 0;

  for (const item of dataSiswa) {
    const existing = await siswaRepository.findOne({
      where: {
        nisn: item.nisn,
      },
    });

    if (!existing) {
      const siswa = siswaRepository.create(item);
      await siswaRepository.save(siswa);
      insertedCount++;
    }
  }

  console.log('======================================');
  console.log(`✔ Seeder Siswa selesai dijalankan.`);
  console.log(`Total data baru ditambahkan : ${insertedCount}`);
  console.log('======================================');
}